server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: django-logs
    static_configs:
      - labels:
          job: django-logs
          service: auth-service
        targets:
          - localhost
        __path__: /var/log/auth-service/*.log

      - labels:
          job: django-logs
          service: tenant-service
        targets:
          - localhost
        __path__: /var/log/tenant-service/*.log
